### ISSUE TITLE
Tab in text body messes up Panel boarders

### ISSUE THREAD

**Issue by nathanrboyer** [FedeClaudi/Term.jl#92] opened 2022-05-16 19:29 UTC
MWE:
```julia
julia> print(Panel("This is some text.\n\tThis is some indented text."))
╭──────────────────────────────────────────────────────────────────────────────────────╮
│  This is some text.                                                                  │
│       This is some indented text.                                                         │
╰──────────────────────────────────────────────────────────────────────────────────────╯

julia> print(Panel("This is some text.\n\tThis is some indented text.", fit = true))
╭───────────────────────────────╮
│  This is some text.           │
│       This is some indented text.  │
╰───────────────────────────────╯
```

**Comment by FedeClaudi** [comment] 2022-05-16 19:42
Thanks for reporting this, not sure what's happening here. Will look into it.

**Comment by FedeClaudi** [comment] 2022-05-18 20:05
The problem boils down to the fact that `textwidth` doesn't include the width of the tab:
```Julia
julia> textwidth("aa\tbb")
4

julia> textwidth("aa    bb")
8

julia> textwidth('\t')
0
```

Everything in `Term` relies upon getting the width of the text right, so this messes everything up. I'm not sure if this is something that Term should take into account though? 
Give it's [definition](https://docs.julialang.org/en/v1/base/strings/#Base.Unicode.textwidth) I would've thought `textwidth` to give the "correct" answer but I guess it ignores escape codes. 

I could have Term replace every `\t` with `    ` when creating renderables, but it feels a bit clunky - what do you think?

**Comment by FedeClaudi** [comment] 2022-05-18 21:17
The next version will have code to left/right align and center two renderables: https://github.com/FedeClaudi/Term.jl/blob/545345c44a90eb0eb4ba91334a5945f87616c1d3/src/layout.jl#L148

with also three shorthand notation function: `⊏, ⊐, ⊔` (left, right, center) which can be combined with the stacking function:

```Julia

p1 = Panel(; width=25)
p2 = Panel(; width=50)

print(
    ⊐(p1,  p2) |> /
  )

                         ╭───────────────────────╮
                         ╰───────────────────────╯
╭────────────────────────────────────────────────╮
╰────────────────────────────────────────────────╯
```


I'm not very happy with the syntax, but the idea is that you can combine justification with stacking to get the result you're looking for.

**Comment by nathanrboyer** [comment] 2022-05-19 15:36
Let's see if Base will fix textwidth instead of creating a workaround in Term.

**Comment by FedeClaudi** [comment] 2022-05-19 20:19
I've opened an issue on Julia - won't fix for Term. Thank you.

**Closed** 2022-05-19 20:19 UTC

**Comment by FedeClaudi** [comment] 2022-05-20 11:36
See the discussion in `Julia`, but basically it's not a bug with `textwidth` is that `\t` is a big headache in general - Term.jl won't deal with it properly and it's discouraged it's used with Term.

**Comment by nathanrboyer** [comment] 2022-05-20 15:10
Makes sense. Thanks for trying.
