### ISSUE TITLE
Feature Request: Add dispaly_name as a parameter in Link function to allow user to pass custom String to be displayed

### ISSUE THREAD

**Issue by VarLad** [FedeClaudi/Term.jl#203] opened 2023-02-17 20:59 UTC
It'd be nice to have the capability to have a display_name parameter (with a default value) in https://github.com/FedeClaudi/Term.jl/blob/master/src/link.jl#L104

**Comment by FedeClaudi** [comment] 2023-02-18 01:52
what do you mean by `display_name`? How would it be used?

**Comment by VarLad** [comment] 2023-02-18 05:18
As in the image I sent in another issue, the `display_name` parameter should decide what to print to the terminal.
For example, if `display_name` is "bell" and filepath is "~/hello.jl", then "bell" should print to the terminal and the link within "bell" should be "~/hello.jl"

**Comment by FedeClaudi** [comment] 2023-02-18 20:34
You mean for [`Link`](https://github.com/FedeClaudi/Term.jl/blob/fbb21d1942f8a3f3c9e03a245483540b9d6f9384/src/link.jl#L104) in general or in the stack traces? In the stack traces users wouldn't have access to it, but perhaps it would be useful in links more generally?

**Comment by VarLad** [comment] 2023-02-19 06:44
@FedeClaudi I mean `Link` in general
It'd be nice if I could give something like `Link("something", "/home/blue/tie.jl", 3)`
That should print `something` and clicking on `something` in a terminal should point to `/home/blue/tie.jl#3`.

Does that make sense?

**Comment by VarLad** [comment] 2023-02-19 06:59
Also, currently writing `Link("/home/blue/tie.jl", 3)` prints `/home/blue/tie.jl` and clicking on it points to `/home/blue/tie.jl#3` but, shouldn't it be pointing to `file:///home/blue/tie.jl#3` instead? 
This can easily be worked around currently by doing `Link("file:///home/blue/tie.jl", 3)` which prints `file:///home/blue/tie.jl` and clicking on that points to `file:///home/blue/tie.jl#3`. Not sure if its intentional or a bug

If you're unfamiliar with the file URI scheme, you can know about it here https://en.wikipedia.org/wiki/File_URI_scheme
`file://` for opening files should work on most Operating Systems and is supported by a lot of terminals

**Comment by FedeClaudi** [comment] 2023-02-19 14:32
Got it, that makes sense. 

It seems like in VSCode links don't work though: https://stackoverflow.com/questions/38458655/how-to-make-paths-clickable-in-visual-studio-code-terminal

To make stacktraces compatible with more platforms I will just leave a link to the whole file path then, but I'll leave the possibility to create `Link` objects with a display_name as you suggested.

**Comment by FedeClaudi** [comment] 2023-02-19 15:20
As such, https://github.com/FedeClaudi/Term.jl/pull/204 will add the new feature (`display_text` parameter) when merged.

**Comment by VarLad** [comment] 2023-02-19 16:14
@FedeClaudi In VSCode, `file:///home/blue/tie.jl` works for link. This can be achieved by `Link("file:///path/to/file.ext", 3)` already but, shouldn't appending `file://` to `filename` parameter be the default?

Refer to my previous comment for more details. Does that make sense?

**Comment by VarLad** [comment] 2023-02-19 16:26
![image](https://user-images.githubusercontent.com/51269425/219960982-6ed86584-f250-4b6b-9da2-d871e9e8f601.png)

(After clicking on the link)

![image](https://user-images.githubusercontent.com/51269425/219961010-06c3221c-065e-4a0a-a9dc-91fec52fed1b.png)

**Comment by FedeClaudi** [comment] 2023-02-19 17:07
yeah but it only works if the displayed text is a valid path in the current directory (or a complete path). If you put anything else it won't find it when I tried. I'll have another look.

**Comment by VarLad** [comment] 2023-02-19 17:24
> yeah but it only works if the displayed text is a valid path in the current directory (or a complete path). If you put anything else it won't find it when I tried. I'll have another look.

Is there a way to get the complete path from the error stacktrace?
With `display_name` you could do `Link(display_name, "file://"*full_path, linenumber)` for the links in stacktrace :)

**Comment by FedeClaudi** [comment] 2023-02-20 01:59
So I've added a `display_text` parameter so you can do something like:
```julia
import Term: Link

l = Link(
    "/Users/federicoclaudi/Documents/Github/Term.jl/src/Term.jl", 1, "display"
)
```
where "display" is printed to the terminal but points to the `.jl` file (linked as `file:///Users/federicoclaudi/Documents/Github/Term.jl/src/Term.jl#1`). The problem is that cmd+click on that will attemt to file a file/folder with the display text, not the underlying link. In this case it looks like for  a folder "display". In your example above ti looks like it "sees" the link but I'm not sure. Currently if the `display_name` parameter is a valid file path in the current working directory cmd+click will work fine, but the actual linked file path is ignored.

**Closed** 2023-02-20 03:06 UTC
