### ISSUE TITLE
HTML display issues in docs

### ISSUE THREAD

**Issue by cormullion** [FedeClaudi/Term.jl#46] opened 2022-03-18 12:05 UTC
Nice package! I saw this in the documentation:

<img width="838" alt="Screenshot 2022-03-18 at 11 54 18" src="https://user-images.githubusercontent.com/52289/158999104-5680dc9e-b1c6-4b9d-923c-7cc292d49df2.png">
 
I don't know why the whitespace isn't being formatted correctly though. Perhaps it's how Documenter does it...

**Comment by FedeClaudi** [comment] 2022-03-18 12:11
Thanks! I hope you enjoy using Term!

Where in the docs is that? It looks fine for me here: https://fedeclaudi.github.io/Term.jl/stable/
![image](https://user-images.githubusercontent.com/17436313/159000744-3584b480-52cf-4576-8a9c-a7937ad595c6.png)

**Comment by cormullion** [comment] 2022-03-18 12:17
It's the first page of the docs: https://fedeclaudi.github.io/Term.jl/dev/

I'm on MacOS Monterey, latest Safari. It's the same on FireFox.

**Comment by FedeClaudi** [comment] 2022-03-18 13:03
mmm bizarre, it looks fine for me anywhere. Perhaps try ctrl+shift+R to reload?

**Comment by YongHee-Kim** [comment] 2022-03-18 14:26
Yeah font seems to be matching... but length of `o` is different in your environment? 
![image](https://user-images.githubusercontent.com/7087745/159021098-788f0ba7-3ed7-4c1e-8632-c7a9f7339dce.png)

**Comment by FedeClaudi** [comment] 2022-03-18 14:50
Whaaat, that's so weird. This is on the docs? 
The `o` seem to have the same width to me, but the spacing between them is different.

**Comment by mostol** [comment] 2022-03-21 21:33
It looks like this might be an issue with the [JuliaMono typeface](https://github.com/cormullion/juliamono). If you swap to another monospace font, it lines up correctly:

https://user-images.githubusercontent.com/76925825/159365961-23072f4f-ae78-4aca-8c29-8896b52668c3.mp4

On closer inspection, it looks like this only happens on lines with bolded areas. JuliaMono is *supposed* to be monospace regardless of weight, but apparently that's not happening here. I checked out the CSS stylesheet and it looks like only `JuliaMono-Regular.woff2` is used, so the browser is doing its own "faux"-bolding to the regular font instead of using the properly-aligned bold version (e.g. `JuliaMono-Bold`), which messes up the whole "monospaced" thing. A quick add of a `@font-family` rule to the CSS seems to confirm this; if I tack on 
```CSS
@font-face {
    font-family: JuliaMono;
    /* Pulling the font file straight from the JulaMono repo for convenience */
    src: url("https://github.com/cormullion/juliamono/blob/master/webfonts/JuliaMono-Bold.woff2?raw=true") format("woff2");
    font-weight: bold;
    text-rendering: optimizeLegibility;
}
```

then it works as intended (and looks really nice, great work on this fantastic package! 😍):

<img width="669" alt="Screen Shot 2022-03-21 at 2 32 58 PM" src="https://user-images.githubusercontent.com/76925825/159367423-a0f91e65-84a5-476d-8b75-620519c2b89c.png">

**Comment by FedeClaudi** [comment] 2022-03-21 23:24
> and looks really nice, great work on this fantastic package!

Thank you, I hope you enjoy it!

Since it's not a Term issue I'll close, unless you need to open to keep track of it but I see you've opened a related one.

**Comment by mostol** [comment] 2022-03-21 23:32
Yeah, go ahead and close it, and hopefully I can get it fixed soon on the Documenter.jl end.

**Closed** 2022-03-22 07:55 UTC

**Comment by cormullion** [comment] 2022-03-22 09:19
Thanks for the cool sleuthing, @mostol !

**Comment by mostol** [comment] 2022-04-05 06:44
Just an update: A quick CSS change was merged into Documenter.jl (see above), so this should theoretically be cleared up whenever the Term.jl docs are built/published with the latest version including the fix.

(Hats off to @cormullion for very conveniently already having the necessary CSS file hosted and ready-to-import.)

**Comment by FedeClaudi** [comment] 2022-04-07 21:18
By the way, is there any advice on how ti display stuff like progress bars? 
To print progress bars Term needs to do some terminal magic, and that doesn't seem to play well with how the docs are rendered: https://fedeclaudi.github.io/Term.jl/dev/adv/progressbars/, any advice?

I also seem to have broken something at the bottom of this page: https://fedeclaudi.github.io/Term.jl/dev/basics/colors/
