### ISSUE TITLE
checking for IOContext prevents using Term for REPL show methods

### ISSUE THREAD

**Issue by ExpandingMan** [FedeClaudi/Term.jl#82] opened 2022-04-25 19:19 UTC
I wish I had caught this back when I asked for the feature and tested it for you, but it's actually a bit sneaky: when the REPL calls `show(io, MIME"text/plain"(), obj)` it wraps the `io` in an `IOContext` but this is not the case for all of the fallback methods.

The problem is that Term explicitly checks for an `IOContext` and turns itself off if it finds one (I think this happens [here](https://github.com/FedeClaudi/Term.jl/blob/master/src/renderables.jl#L31-L40)).  As a result, if you do, e.g.
```
struct TestObj end

show(io::IO, ::MIME"text/plain", ::TestObj) = print(io, Panel("hello!"))
```
you will not get a rendering of the panel, but rather the default REPL `show` method.  The workaround is to explicitly unwrap the `io` within the `show` method before passing it to Term.

I have a few suggestions for workarounds
- Simply remove the check of the `io` for `IOContext`.  In my opinion this would be the best solution as it simplifies everything and there aren't any special checks to get people confused.  I'm not sure if it would be trivial to implement, however, since I assume it works this way right now for reasons internal to Term.jl.
- Have `print` and `tprint` behave differently for `AbstractRenderable`
- Options or kwargs (probably only viable for `tprint`), I don't think this is a very good solution.

Btw, I realize that overloading show methods probably was not one of the original intentions of Term.jl, and indeed, if the `show` methods all worked recursively, Term would be totally unusable for this purpose.  The thing that makes it work really well is that the REPL calls the 3-argument version of `show`, preventing methods overloaded with Term from being called recursively.  I therefore have found it quite nice to define `show(::IO, ::MIME"text/plain", ::Whatever)` using Term.jl and so far have found it works quite well except for these small issues.

**Comment by FedeClaudi** [comment] 2022-05-18 18:02
hey, 

Sorry for the delay in getting back to you on this. 

The reason for checking for the `IOContext` is to distinguish:

```Julia
panel = Panel()
panel

# as opposed to
print(panel)
```

When not using `print` Term shows a compact visualization:
```
Panel <: AbstractRenderable size: Measure (w: 88, h: 2)
```
Otherwise `print(panel)` print's the panel properly. 

The reason for that is to keep the repl clean and not to print the full renderable unless one explicitly asks for that. 
If I understand correctly you want the opposite behavior, you want to actually show the panel, and even with the recent changes this still doesn't work, correct?

**Comment by FedeClaudi** [comment] 2022-05-18 18:15
Okay, I think I've found a work around. 

```
using Term

struct TestObj
  name::String
end

Base.show(io::IO, ::MIME"text/plain", obj::TestObj) = print(io, string(Panel(obj.name; style="red", fit=true)))

obj = TestObj("Mario")
```

gives:
<img width="92" alt="image" src="https://user-images.githubusercontent.com/17436313/169116061-8d13542e-f6c3-47e8-b182-61f772e23aeb.png">

so it should do the trick! Essentially you avoid printing the panel, you just get the string representation which doesn't care about `IO` or `IOContext` etc.

**Comment by FedeClaudi** [comment] 2022-05-18 18:37
I've made a more detailed example on how to do this: https://fedeclaudi.github.io/Term.jl/dev/adv/repr/

**Comment by ExpandingMan** [comment] 2022-05-18 22:33
I am not suggesting that `show` on renderables should be equivalent to `tprint` (it's probably not so bad to define the 3-argument version this way, but it might be confusing).  However, it doesn't seem like such a good idea for renderables to render based on whether they are printing to an `IOContext`.  It's arguably even stranger than that if `string` matches the version that would be printed to a `IOContext{Base.TTY}`.  As far as I know, nothing in `Base` works this way, and this seems problematic because it's other packages have no reason to expect `IOContext` or an non-exported type like `Base.TTY` to control the behavior of renderable in this way.

Off the top of my head, here are suggestions of possible solutions:
- Remove the `io isa IOContext` from the renderable `show` method, and make it always show the `Renderable <: AbstractRenderable` from the two argument method, then add a 3-argument `show` method for `AbstractRenderable` and have that do the full printing.
- Again, remove the `io isa IOContext` but split the behaviors into completely separate functions.

Come to think of it, I suppose either case would be breaking, which sucks, but the more I think about it the more I think it's a bad idea to check `io isa IOContext{Base.TTY}`, it just seems too bizarre for anyone to expect it and I suspect it will lead to all manner of unexpected issues with dependencies of Term.jl down the road.

**Comment by FedeClaudi** [comment] 2022-05-19 20:27
Hi, 

I guess I'm a bit confused about how pritning/show/repr works in Julia still.
From your message my intuition is that `show(io, renderable::AbstractRenderable)` gets called when just showing the renderable in the console while using `print` eventually calls `show(io, ::MIME"text/plain", renderable::AbstractRenderable)` hence why I could use the two methods to distinguish the two behaviors. Is that correct?

**Comment by FedeClaudi** [comment] 2022-05-19 20:43
Based on [this](https://schurkus.com/2018/01/05/julia-print-show-display-dump-what-to-override-what-to-use/) it looks like I had it the other way around. 

This seems to work:
```Julia
"""print renderable"""
function Base.show(io::IO, renderable::AbstractRenderable)
    print(io, string(renderable))
end


"""print concise info in repl"""
function Base.show(io::IO, mime::MIME"text/plain", renderable::AbstractRenderable)
    print(
        io,
        "$(typeof(renderable)) <: AbstractRenderable \e[2msize: $(renderable.measure)\e[0m"
    )
end

```

It prints the concise when needed and the full renderable when using `print` - is this what you had in mind?
I don't think it should be a breaking?

**Comment by ExpandingMan** [comment] 2022-05-20 13:40
I would have done it the other way around.  The 2-argument method is what gets called most often, for example if you have an array of renderables I believe this will try to render all of them.  The 3-argument method pretty much only gets called to display objects to the user in the REPL.  Certainly in my use case I had defined only the 3-argument method for my objects since I wanted them to display a nice panel when I tried to inspect them in the REPL, but not if they were being displayed as part of another object.

However, regardless of which way you do it, I think this would be a major improvement over checking `io isa IOContext{Base.TTY}` since now the functionality is in separate methods and packages don't have to worry about the properties of the `IO` just to get it to display how they want it.

**Comment by FedeClaudi** [comment] 2022-05-20 20:15
I'm so confused...

if I invert the behavior as you suggest:
```Julia

"""print renderable"""
function Base.show(io::IO, renderable::AbstractRenderable)
    print(
        io,
        "$(typeof(renderable)) <: AbstractRenderable \e[2msize: $(renderable.measure)\e[0m"
    )
end


"""print concise info in repl"""
function Base.show(io::IO, mime::MIME"text/plain", renderable::AbstractRenderable)
    print(io, string(renderable))
end

```

I get:
```Julia
julia> [p1, p1]
2-element Vector{Panel}:
 Panel <: AbstractRenderable size: Measure (w: 5, h: 2)
 Panel <: AbstractRenderable size: Measure (w: 5, h: 2)

julia> (p1, p2)
(Panel <: AbstractRenderable size: Measure (w: 5, h: 2), Panel <: AbstractRenderable size: Measure (w: 15, h: 2))

julia> print(p1)
Panel <: AbstractRenderable size: Measure (w: 5, h: 2)
julia> p1
╭───╮
╰───╯
```

I'm happy with how the vector and tuple get displayed, but `julia> p1` and `print(p1)` are the opposite of what I need. 
WIth the code as it was above,  everything's as I'd want it except for a `Tuple`- whyyy
```Julia
julia> [p1, p1]
2-element Vector{Panel}:
 Panel <: AbstractRenderable size: Measure (w: 5, h: 2)
 Panel <: AbstractRenderable size: Measure (w: 5, h: 2)

julia> (p1, p2)
(╭───╮
╰───╯, ╭─────────────╮
╰─────────────╯)

julia> p1
Panel <: AbstractRenderable size: Measure (w: 5, h: 2)

julia> print(p1)
╭───╮
╰───╯
```

**Comment by ExpandingMan** [comment] 2022-05-20 21:38
I don't understand why you would not want what you showed in the first box...
- `Panel` renders nicely whenever its part of another object
- You can easily get the abbreviated view with `print` and you still have `tprint`
- Objects are presented in the REPL with full renderering.

Why is this not ideal?

For what it's worth, the `print` behavior is only because apparently `print` falls back to 2-argument show.  It doesn't have to do that, you could have print show the full object, it's independent of the `show` methods.

**Comment by FedeClaudi** [comment] 2022-05-20 21:58
Okay, I think you are right. 
Basically the problem is that I want `print` to work with renderables, but I was trying to avoid defining `Base.print` for them.

now with:
```Julia

"""print renderable"""
function Base.print(io::IO, renderable::AbstractRenderable)
    print(io, string(renderable))
end


function Base.show(io::IO, renderable::AbstractRenderable)
    w, h = renderable.measure.w, renderable.measure.h
    print(
        io,
        "\e[38;5;117m$(typeof(renderable)) <: AbstractRenderable\e[0m \e[2m(w:$(w), h:$(h))\e[0m"
    )
end


"""print concise info in repl"""
function Base.show(io::IO, mime::MIME"text/plain", renderable::AbstractRenderable)
    w, h = renderable.measure.w, renderable.measure.h
    println(io, string(renderable))
    # println("\e[2m"*"─"^w*"\e[0m")
    print(
        io,
        "\e[38;5;117m$(typeof(renderable)) <: AbstractRenderable\e[0m \e[2m(w:$(w), h:$(h))\e[0m"
    )
end

```

it works like:
```Julia
julia> p = Panel(; width=20)
╭──────────────────╮
╰──────────────────╯
Panel <: AbstractRenderable (w:20, h:2)

julia> [p, p]
2-element Vector{Panel}:
 Panel <: AbstractRenderable (w:20, h:2)
 Panel <: AbstractRenderable (w:20, h:2)

julia> (p, p)
(Panel <: AbstractRenderable (w:20, h:2), Panel <: AbstractRenderable (w:20, h:2))

julia> print(p)
╭──────────────────╮
╰──────────────────╯
julia> p/p
╭──────────────────╮
╰──────────────────╯
╭──────────────────╮
╰──────────────────╯
Term.renderables.Renderable <: AbstractRenderable (w:20, h:4)

```


I think this is the best way actually, having the panels render in the REPL makes for easy prototyping and I hope it won't be a problem for large/complex renderables that might make things cluttered. Perhaps one can check for the renderable's size before printing to console when using `show`...

Thank you very much for the help, I think this  behavior makes a lot more sense now (and sorry if I was a bit slow with it! I appreciate your patience in helping me navigate this..)

**Comment by FedeClaudi** [comment] 2022-05-20 21:59
This also works with your original problem:

```Julia

struct TestObj end

Base.show(io::IO, ::MIME"text/plain", ::TestObj) = print(io, Panel("hello!"))

obj = TestObj()
╭──────────────────────────────────────────────────────────────────────────────────────╮
│  hello!                                                                              │
╰──────────────────────────────────────────────────────────────────────────────────────╯

```

**Comment by ExpandingMan** [comment] 2022-05-20 22:25
Cool, glad it all makes sense.

I agree that the 2, 3 argument `show` situation in `Base` is rather confusing, especially since they exist with `IOContext` which most of the time doesn't even seem to do anything.

And thanks for your work on this package more generally, it's becoming my "go-to" solution for making `show` methods that print nicely.  I had my own [failed experiment in this](https://gitlab.com/ExpandingMan/ShowCases.jl) but I was trying to keep it minimal (i.e. specifically for `show` methods) and I wound up without clear direction and it never really made sense.  Term.jl might be a lot more elaborate, but it's been pretty easy to write pretty `show` methods.  I imagine you're probably like me in that we think there's something oddly wonderful about colored text in the terminal.

**Comment by FedeClaudi** [comment] 2022-05-20 22:28
Indeed I am, my inspiration was `rich` in Python which is just wonderful. I wanted to create something like that for the Julia community and learn some Julia in the process (which I clearly need to). 

There's just something so satisfying in a nice, clear and intuitive terminal output!

I'll be making use of Term for making `show` methods for custom types too

**Comment by FedeClaudi** [comment] 2022-05-21 12:29
![carbon(16)](https://user-images.githubusercontent.com/17436313/169651518-390f836f-24a0-4e37-bcbb-f3e09f8dbf4a.png)

![image](https://user-images.githubusercontent.com/17436313/169651521-7cd7b4a2-c493-4f66-a788-7ceae7f785e3.png)

The next version of Term will have a macro for automatically creating `show` methods for types.
Thanks for the help and inspiration, I've tried to give you a shout out on twitter but I couldn't find you: https://twitter.com/Federico_claudi/status/1527989423031435264?s=20&t=chIf6PLFHnehunsrgArjpA

**Comment by ExpandingMan** [comment] 2022-05-21 15:25
That's awesome!  I'm going to use this all the time!  Love it!

Btw, I didn't close this because I don't know if you made the changes you wanted to resulting from it, but please feel free to close.

**Comment by ExpandingMan** [comment] 2022-05-21 15:27
Also, it would be nice for the macro to call a function that is exported, like a `termshow` or something like that, that would make it pretty easy to use this with or without the macro.

**Comment by FedeClaudi** [comment] 2022-05-21 18:21
That's a great idea, I've done just that so you can use `termshow` on any object and not just types you've defined yourself.

If you're daring you can overwrite `show` for all objects too:
```Julia
Base.show(io::IO, ::MIME"text/plain", obj) = termshow(io, obj)

```

So that showing stuff in the REPR gives:
<img width="280" alt="image" src="https://user-images.githubusercontent.com/17436313/169664423-56b11ce9-003f-4c24-9def-0fb95b62f9a0.png">


I think I've implemented all the functionality for this, so we could close the issue.
But do let me know if there's anything else that you think we could add this was super useful!

**Closed** 2022-05-22 17:30 UTC
